name: Lint
on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter:
          - eslint
          - stylelint
          - prettier
          - tsc
      fail-fast: false
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: shun-shobon/actions/setup-node@master
        with:
          node-version: "lts/*"

      - run: pnpm run lint:${{ matrix.linter }}
