name: pull-request-edited
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
